### ISSUE TITLE
can not prepare the dataset

### ISSUE THREAD

**Issue by chonghaozhang1998** [TaoRuijie/ECAPATDNN#11]
When I followed the Data preparation part in the [link]( https://github.com/clovaai/voxceleb_trainer) and ran the this code `python3 dataprep.py --save_path data --download --user USERNAME --password PASSWORD` , I met with the following error.

> --2021-11-26 14:04:56--  http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa
> Resolving www.robots.ox.ac.uk (www.robots.ox.ac.uk)... 129.67.94.2
> Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:80... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa [following]
> --2021-11-26 14:04:58--  https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa
> Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-11-26 14:04:59 ERROR 404: Not Found.
> 
> Traceback (most recent call last):
>   File "Downloads/voxceleb_trainer-master/dataprep.py", line 176, in <module>
>     download(args,fileparts)
>   File "Downloads/voxceleb_trainer-master/dataprep.py", line 58, in download
>     raise ValueError('Download failed %s. If download fails repeatedly, use alternate URL on the VoxCeleb website.'%url)
> ValueError: Download failed http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa. If download fails repeatedly, use alternate URL on the VoxCeleb website.

How can I solve this problem? Thanks!

**Comment by TaoRuijie** [comment]
Please check here
https://github.com/clovaai/voxceleb_trainer/issues/117

**Comment by chonghaozhang1998** [comment]
I read the link you mentioned. But it seems that my problem is different from this [link](https://github.com/clovaai/voxceleb_trainer/issues/117).

**Comment by TaoRuijie** [comment]
If it can not solve, please try this https://github.com/clovaai/voxceleb_trainer/issues/111

**Comment by chonghaozhang1998** [comment]
It still can not solve. I checked the file in lists/fileparts.txt. The url is already this 

> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa e395d020928bc15670b570a21695ed96
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partab bbfaaccefab65d82b21903e81a8a8020
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partac 017d579a2a96a077f40042ec33e51512
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partad 7bb1e9f70fddc7a678fa998ea8b3ba19
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partaa da070494c573e5c0564b1d11c3b20577
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partab 17fe6dab2b32b48abaf1676429cdd06f
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partac 1de58e086c5edf63625af1cb6d831528
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partad 5a043eb03e15c5a918ee6a52aad477f9
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partae cea401b624983e2d0b2a87fb5d59aa60
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partaf fc886d9ba90ab88e7880ee98effd6ae9
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partag d160ecc3f6ee3eed54d55349531cb42e
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aac_partah 6b84a81b9af72a9d9eecbb3b1f602e65
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_test_wav.zip 185fdc63c3c739954633d50379a3d102
> http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_test_aac.zip 0d2b3ea430a821c33263b5ea37ede312

The problem in this https://github.com/clovaai/voxceleb_trainer/issues/111 is still different from mine.

**Comment by TaoRuijie** [comment]
I do not think that is the same:

It mentioned: "Use https://thor.robots.ox.ac.uk/ instead of http://www.robots.ox.ac.uk/ in all the lines in lists/fileparts.txt"

You do not have 'thor' right?

**Comment by chonghaozhang1998** [comment]
Yes! I misunderstood this sentence "Use https://thor.robots.ox.ac.uk/ instead of http://www.robots.ox.ac.uk/ in all the lines in lists/fileparts.txt". I will have a try. Thanks!

**Comment by chonghaozhang1998** [comment]
It works! Thanks a lot! 😀
