### ISSUE TITLE
result EER

### ISSUE THREAD

**Issue by seacj** [TaoRuijie/ECAPATDNN#6]
I test the result in vox1-O (veri_test.txt) and I get the result below:
EER 1.12%, minDCF 0.0745%
I noticed that the result reported in the README is actually evaluated in Vox1(clean) veri_test2.txt. Still a great work.
By the way, without TTA, I got VEER 1.0052 MinDCF 0.08051 in Vox1(clean).

**Comment by TaoRuijie** [comment]
Yes, I forget to highlight that. Thanks for pointing it out. I have updated the results and mentioned that in readme.
