### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by KAI-LI-JAIST** [TaoRuijie/ECAPATDNN#7]
Hello, thank you so much for contributing this project.
I am training this model recently. I also use one 3090 and the same setting as you. But i need spend about 20 hours for each epoch. Do you know what's the reason?
Thank you so much for your answering in advance.

**Comment by TaoRuijie** [comment]
Did you put your data in SSD?

**Comment by KAI-LI-JAIST** [comment]
My data in /media/user/sda1

**Comment by TaoRuijie** [comment]
sda1 is the name of your disk. You need to check the type of your disk. If it is HDD, the speed for loading the data is very slow. Most of time is using for dataloader (by CPU), so your GPU is empty, which means your GPU device is not training your model.

So you need to put your data into the SSD(Solid-state drive), so CPU can load data very fast. GPU can run 100% util.

**Comment by KAI-LI-JAIST** [comment]
Thank you so much! I will try it.

**Comment by daiyuuu** [comment]
> Thank you so much! I will try it.
Hi, I want to ask, have you fixed this problem? I moved the data to SSD, but the training time is still very long.
