### ISSUE TITLE
About split utterance to matrix

### ISSUE THREAD

**Issue by KAI-LI-JAIST** [TaoRuijie/ECAPATDNN#9]
Excuse me, I noticed that you split utterances into the matrix in the evaluation stage. Could you please explain why you do that?

**Comment by TaoRuijie** [comment]
https://arxiv.org/pdf/2109.03568.pdf

Please check Matrix Score Average (MSA) in 8.1

**Comment by KAI-LI-JAIST** [comment]
Thank you :)
